# Soubor: Makefile
# Reseni ITY-projekt5
# Datum: 4. 5. 2016
# Autor: Ondrej Vales, xvales03
# Fakulta: FIT VUTBR

all:
	latex proj5.tex
	latex proj5.tex
	dvips proj5.dvi
	ps2pdf -sPAPERSIZE=a4 proj5.ps

clean:
	rm -rf *.pdf *.dvi *.ps *.log *.aux *.bbl *.blg *.nav *.out *.snm *.toc