/*
 * synt_anal_types.h
 * Autor: Tomas Zencak
 * Predmet: Formalni jazyky a prekladace
 * Projekt: Implementace interpretu jazyka IFJ15
 * Varianta zadani: a/2/II
 * Datum: 1. 10. 2015
 * Prelozeno: gcc 4.8
 * Tomas Zencak xzenca00
 * Ondrej Vales xvales03
 * Nikola Valesova xvales02
 * Radek Vit xvitra00
 */

#ifndef SYNT_ANAL_TYPES_H_
#define SYNT_ANAL_TYPES_H_

#include "token.h"

typedef enum{
	NTERM_FUNC_DECL_LIST,
	NTERM_FUNC_DECL,
	NTERM_FUNC_DECL_ARG_LIST,
	NTERM_FUNC_DECL_ARG_LIST_CONT,
	NTERM_OPT_FUNC_BODY,
	NTERM_STATEMENT,
	NTERM_COMPOSITE_STATEMENT,
	NTERM_IF_STATEMENT,
	NTERM_ELSE_CLAUSE,
	NTERM_STATEMENT_LIST,
	NTERM_ASSIGNMENT,
	NTERM_FOR_STATEMENT,
	NTERM_RETURN_STATEMENT,
	NTERM_INPUT,
	NTERM_INPUT_CHAIN,
	NTERM_OUTPUT,
	NTERM_OUTPUT_CHAIN,
	NTERM_WHILE_STATEMENT,
	NTERM_DO_WHILE,
	NTERM_WHILE_CLAUSE,
	NTERM_TERM,
	NTERM_VAR_DEF,
	NTERM_OPT_VAR_INIT,
	NTERM_VAR_INIT,
	NTERM_EXPR_END,
	NTERM_EXPR,
	NTERM_FUNC_CALL_ARG_LIST,
	NTERM_TYPE,
	NTERM_COUNT//number of nonterminal types
}Nonterminal;

typedef struct {
	enum {SYNT_NONE, SYNT_NONTERMINAL, SYNT_TERMINAL, SYNT_HANDLE_START, SYNT_EXPR_START} type;
	union{
		TokenType terminal;
		Nonterminal nonterminal;
	};
}SyntacticElement;

typedef enum{
	RULE_ERROR,
	RULE_FUNC_DECL_LIST__FUNC_DECL_FUNC_DECL_LIST,
	RULE_FUNC_DECL_LIST__EPSILON,
	RULE_FUNC_DECL,
	RULE_FUNC_DECL_ARG_LIST__DECL_ARG_CONT,
	RULE_FUNC_DECL_ARG_LIST__EPSILON,
	RULE_FUNC_DECL_ARG_LIST_CONT__COMMA_DECL_ARG_CONT,
	RULE_FUNC_DECL_ARG_LIST_CONT__EPSILON,
	RULE_OPT_FUNC_BODY__SEMICOLON,
	RULE_OPT_FUNC_BODY__COMPOSITE_STATEMENT,
	RULE_STATEMENT__COMPOSITE_STATEMENT,
	RULE_STATEMENT__IF_STATEMENT,
	RULE_STATEMENT__ASSIGNMENT,
	RULE_STATEMENT__FOR_STATEMENT,
	RULE_STATEMENT__RETURN_STATEMENT,
	RULE_STATEMENT__INPUT,
	RULE_STATEMENT__OUTPUT,
	RULE_STATEMENT__VAR_DEF,
	RULE_STATEMENT__WHILE_STATEMENT,
	RULE_STATEMENT__DO_WHILE,
	RULE_COMPOSITE_STATEMENT,
	RULE_IF_STATEMENT,
	RULE_ELSE_CLAUSE__ELSE_STATEMENT,
	RULE_ELSE_CLAUSE__EPSILON,
	RULE_STATEMENT_LIST__STATEMENT_STATEMENT_LIST,
	RULE_STATEMENT_LIST__EPSILON,
	RULE_ASSIGNMENT,
	RULE_FOR_STATEMENT,
	RULE_RETURN_STATEMENT,
	RULE_INPUT,
	RULE_INPUT_CHAIN__ID_INPUT_CHAIN,
	RULE_INPUT_CHAIN__EPSILON,
	RULE_OUTPUT,
	RULE_OUTPUT_CHAIN__TERM_OUTPUT_CHAIN,
	RULE_OUTPUT_CHAIN__EPSILON,
	RULE_TERM__ID,
	RULE_TERM__NUMBER,
	RULE_TERM__REAL,
	RULE_TERM__STRING,	
	RULE_VAR_DEF__TYPE_ID_OPT_VAR_INIT,
	RULE_VAR_DEF__AUTO_ID_VAR_INIT,
	RULE_OPT_VAR_INIT__VAR_INIT,
	RULE_OPT_VAR_INIT__EPSILON,
	RULE_VAR_INIT__ASSIGN_EXPR,
	RULE_WHILE_STATEMENT,
	RULE_DO_WHILE,
	RULE_WHILE_CLAUSE,
	RULE_EXPR_END__EPSILON,
	RULE_TYPE__INT,
	RULE_TYPE__DOUBLE,
	RULE_TYPE__STRING,
	RULES_EXPRESSIONS_START, //separator of expr and non-expr rules
	RULE_EXPR__PARENTHESES_EXPR,
	RULE_EXPR__LEX_ID,
	RULE_EXPR__LEX_NUMBER,
	RULE_EXPR__LEX_REAL_NUMBER,
	RULE_EXPR__LEX_STRING_LITERAL,
	RULE_EXPR__ADD,
	RULE_EXPR__SUB,
	RULE_EXPR__MULT,
	RULE_EXPR__DIV,
	RULE_EXPR__GREATER,
	RULE_EXPR__LESS,
	RULE_EXPR__GREATEREQ,
	RULE_EXPR__LESSEQ,
	RULE_EXPR__EQ,
	RULE_EXPR__NEQ,
	RULE_EXPR__FUNC_NO_PARAM,
	RULE_EXPR__FUNC_ONE_PARAM,
	RULE_EXPR__FUNC_PARAM_LIST,
	RULES_ARGUMENTS_START, //from here, reduce to [func_call_arg_list]
	RULE_FUNC_CALL_ARG_LIST__EXPR_EXPR,
	RULE_FUNC_CALL_ARG_LIST__FUNC_CALL_ARG_LIST_EXPR,
	RULES_END
}Rule;

#endif //SYNT_ANAL_TYPES_H_
